### ISSUE TITLE
Acceptance invitation content 

### ISSUE THREAD

**Issue by pmandler** [iesl/openreview-scripts#187]
The acceptance invitation content value-radio should be updated to match the meta review.

**Comment by melisabok** [comment]
is this still open or you need help with the acceptance invitation?

cc/ @mspector

**Comment by pmandler** [comment]
I could use help.  In submissionProcess_conference.template the acceptanceInvite says values can be Accepted, Rejected, or Pending.  But I've been told that it should be the same as the meta review which is Oral, Poster, Workshop or Rejected.

**Comment by mspector** [comment]
"value-dropdown": [
"Accept (Oral)",
"Accept (Poster)",
"Reject",
"Invite to Workshop Track"
]
