### ISSUE TITLE
Delete/Restore doesn't work

### ISSUE THREAD

**Issue by pmandler** [iesl/openreview-scripts#451]
After deleting a comment or a review, it shows a faded version with a “Restore” button.  When I press the button it appears that it was restored, but the next time I load the page it is still grayed out and has the "Restore” button instead of the delete or edit buttons.

**Comment by mspector** [comment]
@pmandler thanks pam - but could you post this issue in the "openreview" repo instead?

**Comment by pmandler** [comment]
moved to openreview
